---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    name: Scan Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build
        id: build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Generate .trivyignore
        id: generate_trivyignore
        run: |
          curl -sSL https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-python-base/refs/heads/main/.trivyignore --output analytical-platform-airflow-python-base-trivyignore

          if [[ ! -f .trivyignore ]]; then
            mv analytical-platform-airflow-python-base-trivyignore .trivyignore
          else
            cat analytical-platform-airflow-python-base-trivyignore >> .trivyignore
          fi

      - name: Scan
        id: scan
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
